//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvenueEntrega.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvenueEntrega.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string CadastrarMapaViewModel_AttributeName_File {
            get {
                return ResourceManager.GetString("CadastrarMapaViewModel_AttributeName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        public static string CadastrarMapaViewModel_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("CadastrarMapaViewModel_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle autonomy (0.00).
        /// </summary>
        public static string CalculoCustoViewModel_AttributeName_Autonomia {
            get {
                return ResourceManager.GetString("CalculoCustoViewModel_AttributeName_Autonomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string CalculoCustoViewModel_AttributeName_Destino {
            get {
                return ResourceManager.GetString("CalculoCustoViewModel_AttributeName_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        public static string CalculoCustoViewModel_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("CalculoCustoViewModel_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string CalculoCustoViewModel_AttributeName_Origem {
            get {
                return ResourceManager.GetString("CalculoCustoViewModel_AttributeName_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel cost (0.00).
        /// </summary>
        public static string CalculoCustoViewModel_AttributeName_ValorCombustivel {
            get {
                return ResourceManager.GetString("CalculoCustoViewModel_AttributeName_ValorCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        public static string ExcluirMapaViewModel_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("ExcluirMapaViewModel_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string FileServices_LoadMapaFromFile_Error_Message {
            get {
                return ResourceManager.GetString("FileServices_LoadMapaFromFile_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not processed..
        /// </summary>
        public static string FileServices_LoadMapaFromFile_Fail_Message {
            get {
                return ResourceManager.GetString("FileServices_LoadMapaFromFile_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File processed with success..
        /// </summary>
        public static string FileServices_LoadMapaFromFile_Success_Message {
            get {
                return ResourceManager.GetString("FileServices_LoadMapaFromFile_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to calculate the lowest cost for the route.
        /// </summary>
        public static string MapaController_HttpGet_Action_CalcularCusto_ViewBag_Message {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_CalcularCusto_ViewBag_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate cost for route:.
        /// </summary>
        public static string MapaController_HttpGet_Action_CalcularCusto_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_CalcularCusto_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to register a new map.In case it already exist will be overrided.
        /// </summary>
        public static string MapaController_HttpGet_Action_Create_ViewBag_Message {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_Create_ViewBag_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new map:.
        /// </summary>
        public static string MapaController_HttpGet_Action_Create_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_Create_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exclude this map?.
        /// </summary>
        public static string MapaController_HttpGet_Action_Delete_ViewBag_Message {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_Delete_ViewBag_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete map:.
        /// </summary>
        public static string MapaController_HttpGet_Action_Delete_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_Delete_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred maps.
        /// </summary>
        public static string MapaController_HttpGet_Action_Index_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_Index_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred maps.
        /// </summary>
        public static string MapaController_HttpGet_Action_List_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpGet_Action_List_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate cost for route:.
        /// </summary>
        public static string MapaController_HttpPost_Action_CalcularCusto_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpPost_Action_CalcularCusto_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading file must be specificated..
        /// </summary>
        public static string MapaController_HttpPost_Action_Create_ViewBag_Message {
            get {
                return ResourceManager.GetString("MapaController_HttpPost_Action_Create_ViewBag_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the map must be specificated..
        /// </summary>
        public static string MapaController_HttpPost_Action_Create_ViewBag_Message2 {
            get {
                return ResourceManager.GetString("MapaController_HttpPost_Action_Create_ViewBag_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new map:.
        /// </summary>
        public static string MapaController_HttpPost_Action_Create_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpPost_Action_Create_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete map:.
        /// </summary>
        public static string MapaController_HttpPost_Action_Delete_ViewBag_Title {
            get {
                return ResourceManager.GetString("MapaController_HttpPost_Action_Delete_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_AlterarMapa_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_AlterarMapa_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_AlterarMapa_Fail_Message {
            get {
                return ResourceManager.GetString("MapaServices_AlterarMapa_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map not found..
        /// </summary>
        public static string MapaServices_AlterarMapa_Fail2_Message {
            get {
                return ResourceManager.GetString("MapaServices_AlterarMapa_Fail2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map updated with success..
        /// </summary>
        public static string MapaServices_AlterarMapa_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_AlterarMapa_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_CalcularRota_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_CalcularRota_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map not found..
        /// </summary>
        public static string MapaServices_CalcularRota_Fail_Message {
            get {
                return ResourceManager.GetString("MapaServices_CalcularRota_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_CalcularRota_Fail2_Message {
            get {
                return ResourceManager.GetString("MapaServices_CalcularRota_Fail2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string MapaServices_CalcularRota_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_CalcularRota_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_EncontrarMapaPor_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarMapaPor_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map not found..
        /// </summary>
        public static string MapaServices_EncontrarMapaPor_Fail_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarMapaPor_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map found..
        /// </summary>
        public static string MapaServices_EncontrarMapaPor_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarMapaPor_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_EncontrarTodosMapas_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarTodosMapas_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps found..
        /// </summary>
        public static string MapaServices_EncontrarTodosMapas_Failed_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarTodosMapas_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} map(s).
        /// </summary>
        public static string MapaServices_EncontrarTodosMapas_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_EncontrarTodosMapas_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_ExcluirMapa_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_ExcluirMapa_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map not found..
        /// </summary>
        public static string MapaServices_ExcluirMapa_Fail_Message {
            get {
                return ResourceManager.GetString("MapaServices_ExcluirMapa_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map removed with success..
        /// </summary>
        public static string MapaServices_ExcluirMapa_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_ExcluirMapa_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_InserirMapa_Error_Message {
            get {
                return ResourceManager.GetString("MapaServices_InserirMapa_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string MapaServices_InserirMapa_Fail_Message {
            get {
                return ResourceManager.GetString("MapaServices_InserirMapa_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map added with success..
        /// </summary>
        public static string MapaServices_InserirMapa_Success_Message {
            get {
                return ResourceManager.GetString("MapaServices_InserirMapa_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map name must be specified..
        /// </summary>
        public static string MapaSpecification_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("MapaSpecification_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map must have routes..
        /// </summary>
        public static string MapaSpecification_AttributeName_Rotas {
            get {
                return ResourceManager.GetString("MapaSpecification_AttributeName_Rotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string MapaViewModel_AttributeName_Arquivo {
            get {
                return ResourceManager.GetString("MapaViewModel_AttributeName_Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MapaViewModel_AttributeName_Id {
            get {
                return ResourceManager.GetString("MapaViewModel_AttributeName_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        public static string MapaViewModel_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("MapaViewModel_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle autonomy cannot be zero..
        /// </summary>
        public static string ProblemSpecification_AttributeName_AutonomiaVeiculo {
            get {
                return ResourceManager.GetString("ProblemSpecification_AttributeName_AutonomiaVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination must be specified..
        /// </summary>
        public static string ProblemSpecification_AttributeName_Destino {
            get {
                return ResourceManager.GetString("ProblemSpecification_AttributeName_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A map name must be specified..
        /// </summary>
        public static string ProblemSpecification_AttributeName_NomeMapa {
            get {
                return ResourceManager.GetString("ProblemSpecification_AttributeName_NomeMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin must be specified..
        /// </summary>
        public static string ProblemSpecification_AttributeName_Origem {
            get {
                return ResourceManager.GetString("ProblemSpecification_AttributeName_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fuel value cannot be zero..
        /// </summary>
        public static string ProblemSpecification_AttributeName_ValorCombustivel {
            get {
                return ResourceManager.GetString("ProblemSpecification_AttributeName_ValorCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ResultadoCustoViewModel_AttributeName_Caminho {
            get {
                return ResourceManager.GetString("ResultadoCustoViewModel_AttributeName_Caminho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        public static string ResultadoCustoViewModel_AttributeName_CustoTotal {
            get {
                return ResourceManager.GetString("ResultadoCustoViewModel_AttributeName_CustoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route must have a destination..
        /// </summary>
        public static string RotaSpecification_AttributeName_Destino {
            get {
                return ResourceManager.GetString("RotaSpecification_AttributeName_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route must have a origin..
        /// </summary>
        public static string RotaSpecification_AttributeName_Origem {
            get {
                return ResourceManager.GetString("RotaSpecification_AttributeName_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectList_Null_Item {
            get {
                return ResourceManager.GetString("SelectList_Null_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string View_Layout_Cultura_Ingles {
            get {
                return ResourceManager.GetString("View_Layout_Cultura_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string View_Layout_Cultura_Portugues {
            get {
                return ResourceManager.GetString("View_Layout_Cultura_Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Views_Mapa_CadastrarMapaPartialView_Button_Cadastrar {
            get {
                return ResourceManager.GetString("Views_Mapa_CadastrarMapaPartialView_Button_Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Views_Mapa_CadastrarMapaPartialView_Button_Cancelar {
            get {
                return ResourceManager.GetString("Views_Mapa_CadastrarMapaPartialView_Button_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Mapa_CadastrarMapaPartialView_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Mapa_CadastrarMapaPartialView_Button_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Views_Mapa_CalcularCustoPartialView_Button_Calcular {
            get {
                return ResourceManager.GetString("Views_Mapa_CalcularCustoPartialView_Button_Calcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Views_Mapa_CalcularCustoPartialView_Button_Cancelar {
            get {
                return ResourceManager.GetString("Views_Mapa_CalcularCustoPartialView_Button_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Mapa_CalcularCustoPartialView_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Mapa_CalcularCustoPartialView_Button_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Views_Mapa_ExcluirMapaPartialView_Button_Cancelar {
            get {
                return ResourceManager.GetString("Views_Mapa_ExcluirMapaPartialView_Button_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Views_Mapa_ExcluirMapaPartialView_Button_Excluir {
            get {
                return ResourceManager.GetString("Views_Mapa_ExcluirMapaPartialView_Button_Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Mapa_ExcluirMapaPartialView_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Mapa_ExcluirMapaPartialView_Button_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New map.
        /// </summary>
        public static string Views_Mapa_ListaMapasPartialView_Button_Novo {
            get {
                return ResourceManager.GetString("Views_Mapa_ListaMapasPartialView_Button_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Mapa_ResultadoCustoPartialView_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Mapa_ResultadoCustoPartialView_Button_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Mapa_SucessoPartialView_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Mapa_SucessoPartialView_Button_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenue Delivery.
        /// </summary>
        public static string Views_Shared_Layout_WindowModal_Application_Title {
            get {
                return ResourceManager.GetString("Views_Shared_Layout_WindowModal_Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Views_Shared_Layout_WindowModal_Button_Cancelar {
            get {
                return ResourceManager.GetString("Views_Shared_Layout_WindowModal_Button_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Views_Shared_Layout_WindowModal_Button_Fechar {
            get {
                return ResourceManager.GetString("Views_Shared_Layout_WindowModal_Button_Fechar", resourceCulture);
            }
        }
    }
}
